### ISSUE TITLE
Universal version (Linux, OSX, Win)

### ISSUE THREAD

**Issue by ABeltramo** [tihmstar/otachecker#1]
I created a version wich don't rely on Apple libraries to work that does the same you do.
It's rewritten in pure C++ with just two dependency and it's tested on Linux. I think it works also on other platforms.
If anyone would test it or make any modification contact me!
[Otachecker-u](https://github.com/ABeltramo/otachecker-u)
I'd put a credit on you in absence of a license (even if I don't use any of your code).

**Comment by tihmstar** [comment]
Hey, i like what you did there :)
Even though there are some bugs (crashes with "-h" parameter) and some
optical stuff i'd make different (separate devices by a new line like in
this pic https://twitter.com/tihmstar/status/656917276785057794 and add a
help screen if launched with "-h"), it's still very good work.
Would be really cool if you could implement these suggestions.
I'm gonna share this on twitter so people can see :D

Nice too see that someone is interested those kind of projects ;P

**Comment by ABeltramo** [comment]
Hello! I'm happy to read your positive comment!
I'm still surprised the code it's working! I'll write it in a afternoon using for the first time the "strange" anycast of boost and the awful Apple Plists format (why developers have always to make simple things difficult?).
I'll implement your suggestions right now!
I'm also interested in adding the data from api.ineal.me but didn't find the correct way to do so. Suggestion?

**Comment by ABeltramo** [comment]
I'm happy to say that both your suggestions were correctly implemented. :smile:

**Comment by tihmstar** [comment]
i don't really see a point to use api.ineal.me since the tool's task is to
show infos about ota firmwares, which can't be fetched from api.ineal.me
